name: 'complete_journey'
version: '1.1.0'
require-dbt-version: ">=1.2.3"
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# packages-install-path: dbt_modules

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

models:
  # Source data from Dunnhumby
  complete_journey:
    +materialized: view
  
    # All source data renamed and recast once
    #   - note: due to cleanliness of source data, some tables
    #           have simply been created directly in the warehouse schema
    staging:
      +schema: staging
    
    # Dimensionally modelled tables
    # Suitable for direct query by data-savvy users
    # Note - Intermediate directory includes queries useful for reporting,
    #        but not suitable for direct query on their own
    warehouse:
      +schema: warehouse

      intermediate:
        +materialized: ephemeral
    
    # Tables or views suitable for most reporting requirements
    # Combines fact and dimension tables together correctly
    # Typically materialized as a partitioned, clustered table for performance
    marts:
      +schema: marts
      +materialized: table

seeds:
  +schema: seed_data

tests:
  complete_journey:
    store_failures: true